---
on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  create_draft_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref_name }}
          version: ${{ github.ref_name }}

  # release:
  #   strategy:
  #     matrix:
  #       include:
  #         - os: ubuntu-latest
  #           artifact_file: hifumi-linux-amd64.tgz
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Setup Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version-file: './go.mod'
  #     - name: Build release
  #       run: |
  #         go build -o hifumi cmd/hifumi/main.go
