---
name: Tests

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  gotest:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - name: Unit Tests
        run: go test -coverprofile=coverage.out -covermode=count ./shogi/... ./engine/...

